### ISSUE TITLE
Backward compatibility with the previous version

### ISSUE THREAD

**Issue by alexanderkozlenko** [cla-assistant/github-action#24]
Is it possible to add the ability for exporting metadata from the previous version of the CLA assistant (https://cla-assistant.io) in JSON format that will be accepted by the new version (GitHub Action)? Currently, the previous version exports only in CSV format, and there is no way to upgrade to the new version keeping the list of contributors who already signed agreement.

**Comment by ibakshay** [comment]
Hi @alexanderkozlenko, thank you for reaching out to us. You are right. The `CLA Assistant` exports only in CSV format and exporting in JSON format is not supported yet. This seems like a **must-have feature** as it will totally automate the signature migration process. Feel free to create a PR with this feature or promote it among developers, who could contribute it :) . Otherwise, I am afraid it might take a bit longer to implement this feature request 😞
